name: Update Dependency Graph

on: workflow_call

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: default_x64_latest
    steps:
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-submission@v2
